#ifndef ITS_ISO_SERVER_SOCKET_RECEIVER_MSG_H_LOCAL
#define ITS_ISO_SERVER_SOCKET_RECEIVER_MSG_H_LOCAL

#define ITS_ISO_SERVER_RECEIVER_MSG				0x03000000
#define ITS_ISO_SERVER_RECEIVER_RECEIVED		(ITS_ISO_SERVER_RECEIVER_MSG | 0x00000001)
#define ITS_ISO_SERVER_RECEIVER_EXCEPTION		(ITS_ISO_SERVER_RECEIVER_MSG | 0x0000FFFF)

#include "ItsIso14827SocketReceiverMsgs.h"

#endif