#ifndef ITS_ISO_SERVER_ACCEPTOR_MSG_H_LOCAL
#define ITS_ISO_SERVER_ACCEPTOR_MSG_H_LOCAL

#define ITS_ISO_SERVER_ACCEPTOR_MSG				0x02000000
#define ITS_ISO_SERVER_ACCEPTOR_CONNECTED		(ITS_ISO_SERVER_ACCEPTOR_MSG | 0x00000001)
#define ITS_ISO_SERVER_ACCEPTOR_EXCEPTION		(ITS_ISO_SERVER_ACCEPTOR_MSG | 0x0000FFFF)

#include "ItsIso14827SocketAcceptorMsgs.h"

#endif