#ifndef GITSN_DSRCMSG_TEST_SCENARIO_MSG_H_LOCAL
#define GITSN_DSRCMSG_TEST_SCENARIO_MSG_H_LOCAL

#define GITSN_DSRCMSG_TEST_SCENARIO_CORE_MSG				0xF0000000
#define GITSN_DSRCMSG_TEST_SCENARIO_DO_DEFAULT				(GITSN_DSRCMSG_TEST_SCENARIO_CORE_MSG | 0x00000001)
#define GITSN_DSRCMSG_TEST_SCENARIO_TRIGGER					(GITSN_DSRCMSG_TEST_SCENARIO_CORE_MSG | 0x0000000FF)

#define	GITSN_DSRCMSG_TEST_SCENARIO_COMMAND_MSG				0x0F000000
#define GITSN_DSRCMSG_TEST_SCENARIO_START					(GITSN_DSRCMSG_TEST_SCENARIO_COMMAND_MSG | 0x00000001)
#define GITSN_DSRCMSG_TEST_SCENARIO_STOP					(GITSN_DSRCMSG_TEST_SCENARIO_COMMAND_MSG | 0x00000002)
#define GITSN_DSRCMSG_TEST_SCENARIO_SETUP					(GITSN_DSRCMSG_TEST_SCENARIO_COMMAND_MSG | 0x00000003)


#define GITSN_DSRCMSG_TEST_SCENARIO_IPC_MSG					0x00F00000
// NOTIFY
#define GITSN_DSRCMSG_TEST_SCENARIO_NOTIFY_STATE			(GITSN_DSRCMSG_TEST_SCENARIO_IPC_MSG | 0x00000001)
#define GITSN_DSRCMSG_TEST_SCENARIO_NOTIFY_INFO				(GITSN_DSRCMSG_TEST_SCENARIO_IPC_MSG | 0x00000002)
#define GITSN_DSRCMSG_TEST_SCENARIO_NOTIFY_ERROR			(GITSN_DSRCMSG_TEST_SCENARIO_IPC_MSG | 0x00000003)
// VALIDATE
#define GITSN_DSRCMSG_TEST_SCENARIO_VALIDATE_REQUEST		(GITSN_DSRCMSG_TEST_SCENARIO_IPC_MSG | 0x00000004)
#define GITSN_DSRCMSG_TEST_SCENARIO_VALIDATE_RESPONSE		(GITSN_DSRCMSG_TEST_SCENARIO_IPC_MSG | 0x00000005)
// INITIALIZE
#define GITSN_DSRCMSG_TEST_SCENARIO_UI_CONFIGURE			(GITSN_DSRCMSG_TEST_SCENARIO_IPC_MSG | 0x00000006)

#define GITSN_DSRCMSG_TEST_SCENARIO_SEND_DONE				(GITSN_DSRCMSG_TEST_SCENARIO_IPC_MSG | 0x0000000F)

#define GITSN_DSRCMSG_TEST_SCENARIO_TEST_MSG				0x0000F000
#define GITSN_DSRCMSG_TEST_SCENARIO_TEST_VALIDATE			(GITSN_DSRCMSG_TEST_SCENARIO_TEST_MSG | 0x00000001)
#define GITSN_DSRCMSG_TEST_SCENARIO_TEST_ENC				(GITSN_DSRCMSG_TEST_SCENARIO_TEST_MSG | 0x00000002)
#define GITSN_DSRCMSG_TEST_SCENARIO_TEST_DEC				(GITSN_DSRCMSG_TEST_SCENARIO_TEST_MSG | 0x00000003)
#include "GitsnDSRCMsgTestScenarioMsgs.h"


DZ1_CPPLINK bool_t GitsnDSRCMsgTestScenario_commandMsgInit(void* task, Dz1Error* err);

#endif // GITSN_DSRCMSG_TEST_SCENARIO_MSG_H_LOCAL

