#ifndef GITSN_DSRC_EMULATOR_MSG_H_LOCAL
#define GITSN_DSRC_EMULATOR_MSG_H_LOCAL

#define GITSN_DSRC_EMULATOR_CORE_MSG			0xF0000000
#define GITSN_DSRC_EMULATOR_DO_DEFAULT			(GITSN_DSRC_EMULATOR_CORE_MSG | 0x00000001)

#define GITSN_DSRC_EMULATOR_TEST_MSG			0x0F000000
#define GITSN_DSRC_EMULATOR_TEST_INIT			(GITSN_DSRC_EMULATOR_TEST_MSG | 0x00000001)
#define GITSN_DSRC_EMULATOR_TEST_SEND			(GITSN_DSRC_EMULATOR_TEST_MSG | 0x00000002)
#define GITSN_DSRC_EMULATOR_TEST_TDP_SEND			(GITSN_DSRC_EMULATOR_TEST_MSG | 0x00000004)
#define GITSN_DSRC_EMULATOR_TEST_CLEAR			(GITSN_DSRC_EMULATOR_TEST_MSG | 0x00000008)




#include "GitsnDsrcEmulatorMsgs.h"


DZ1_CPPLINK bool_t GitsnDsrcmEmulator_msgInit(void* task, Dz1Error* err);
DZ1_CPPLINK bool_t GitsnDsrcEmulator_clientSockMsgInit(void* task, Dz1Error* err);
DZ1_CPPLINK void GitsnDsrcEmulator_clientSockMsgClear(void* task);


#endif // GITSN_DSRC_EMULATOR_MSG_H_LOCAL
