#ifndef SCENARIO_ENGINE_MSG_H_LOCAL
#define SCENARIO_ENGINE_MSG_H_LOCAL

#define SCENARIO_ENGINE_CORE_MSG							0xF0000000
#define SCENARIO_ENGINE_DO_DEFAULT							(SCENARIO_ENGINE_CORE_MSG | 0x00000001)

#define SCENARIO_ENGINE_COMMAND_MSG							0x0F000000
// to scenario
#define SCENARIO_ENGINE_COMMAND_START						(SCENARIO_ENGINE_COMMAND_MSG | 0x00000001)
#define SCENARIO_ENGINE_COMMAND_STOP						(SCENARIO_ENGINE_COMMAND_MSG | 0x00000002)
#define SCENARIO_ENGINE_COMMAND_SETUP						(SCENARIO_ENGINE_COMMAND_MSG | 0x00000003)	// 수정 필요

#define	SCENARIO_ENGINE_IPC_MSG								0x00F00000
// NOTIFY
#define SCENARIO_ENGINE_NOTIFY_STATE						(SCENARIO_ENGINE_IPC_MSG | 0X00000001)
#define SCENARIO_ENGINE_NOTIFY_INFO							(SCENARIO_ENGINE_IPC_MSG | 0X00000002)
#define SCENARIO_ENGINE_NOTIFY_ERROR						(SCENARIO_ENGINE_IPC_MSG | 0X00000003)
// VALIDATE
#define SCENARIO_ENGINE_VALIDATE_REQUEST					(SCENARIO_ENGINE_IPC_MSG | 0X00000004)
#define SCENARIO_ENGINE_VALIDATE_RESPONSE					(SCENARIO_ENGINE_IPC_MSG | 0X00000005)
// INITAILIZE
#define SCENARIO_ENGINE_UI_CONFIGURE						(SCENARIO_ENGINE_IPC_MSG | 0X00000006)
// DONE
#define SCENARIO_ENGINE_RECEIVED_SCENARIO_DONE				(SCENARIO_ENGINE_IPC_MSG | 0X0000000F)

#include "ScenarioEngineMsgs.h"


DZ1_CPPLINK bool_t ScenarioEngine_webSockMsgInit(void* task, Dz1Error *err);
DZ1_CPPLINK	bool_t ScenarioEngine_IPCMsgInit(void* task, Dz1Error *err);


#endif // SCENARIO_ENGINE_MSG_H_LOCAL
