//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by dz1_code_gen_gui.rc
//
#define IDC_BUTTON_NO                   3
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_MAIN_DLG                    102
#define IDR_MAINFRAME                   128
#define IDD_TDO_DLG                     129
#define IDD_TDO_LIST_DLG                130
#define IDD_TDO_COLUMN_DLG              131
#define IDD_DIALOG1                     132
#define IDD_TODEC_DLG                   132
#define IDD_TODEC_CONFIG_DLG            133
#define IDD_STRING_DLG                  134
#define IDD_TEXT_PAD_DLG                135
#define IDD_TODEC_CONFIG2_DLG           136
#define IDD_DIALOG3                     138
#define IDD_TODEC_PUBLISH_DLG           138
#define IDC_EDIT_LIST_ARG1              1000
#define IDC_COMBO_LIST_MODE             1001
#define IDC_EDIT_LIST_ARG2              1002
#define IDC_EDIT_LIST_ARG3              1003
#define IDC_EDIT_LIST_ARG4              1004
#define IDC_STATIC_LIST_ARG1            1005
#define IDC_STATIC_LIST_ARG2            1006
#define IDC_STATIC_LIST_ARG3            1007
#define IDC_STATIC_LIST_ARG4            1008
#define IDC_BUTTON_LIST_CODE_GEN        1009
#define IDC_COMBO_STUB_MODE             1010
#define IDC_EDIT_TDO_FILE               1010
#define IDC_EDIT_STUB_ARG1              1011
#define IDC_BUTTON_TDO_FILE             1011
#define IDC_EDIT_STUB_ARG2              1012
#define IDC_TREE_TDO_INCLUDE            1012
#define IDC_EDIT_STUB_ARG3              1013
#define IDC_LIST_TDO_UNKNOWN            1013
#define IDC_EDIT_STUB_ARG4              1014
#define IDC_LIST_TDO_OBJECT             1014
#define IDC_BUTTON_LIST_CODE_GEN2       1015
#define IDC_BUTTON_STUB_CODE_GEN        1015
#define IDC_STATIC_STUB_ARG1            1016
#define IDC_STATIC_STUB_ARG2            1017
#define IDC_STATIC_STUB_ARG3            1018
#define IDC_STATIC_STUB_ARG4            1019
#define IDC_BUTTON1                     1020
#define IDC_BUTTON_TDO                  1020
#define IDC_BUTTON_CREATE_LIST_CONTROL  1021
#define IDC_COMBO_PARSER_MODE           1021
#define IDC_BUTTON_TODEC_DEL            1021
#define IDC_BUTTON_SOURCE               1021
#define IDC_TREE_SOURCES                1022
#define IDC_EDIT_PARSER_ARG1            1022
#define IDC_BUTTON_TODEC_SEQ_DN         1022
#define IDC_BUTTON_SAVE_TO_TDC          1022
#define IDC_LIST_COLUMNS                1023
#define IDC_EDIT_PARSER_ARG2            1023
#define IDC_BUTTON_TODEC_SEQ_UP         1023
#define IDC_BUTTON_ADD                  1024
#define IDC_EDIT_PARSER_ARG3            1024
#define IDC_BUTTON_TODEC_SEQ_ADD        1024
#define IDC_BUTTON_REMOVE               1025
#define IDC_EDIT_LIST_ARG8              1025
#define IDC_EDIT_PARSER_ARG4            1025
#define IDC_BUTTON_TODEC_SEQ_DEL        1025
#define IDC_EDIT_ORDER                  1026
#define IDC_BUTTON_PARSER_CODE_GEN      1026
#define IDC_BUTTON_SAVE                 1026
#define IDC_EDIT2                       1027
#define IDC_EDIT_NAME                   1027
#define IDC_STATIC_PARSER_ARG1          1027
#define IDC_BUTTON_OBJECT_SRC           1027
#define IDC_EDIT_ALTERNATE_FUNCTION     1027
#define IDC_EDIT_FILE_BASE_NAME         1027
#define IDC_BUTTON_OK                   1028
#define IDC_STATIC_PARSER_ARG2          1028
#define IDC_BUTTON_TODEC_SEQ_MOD        1028
#define IDC_STATIC_PARSER_ARG3          1029
#define IDC_BUTTON_OBJECT_HDR           1029
#define IDC_STATIC_PARSER_ARG4          1030
#define IDC_LIST_TODEC                  1030
#define IDC_COMBO_SHELL_MODE            1031
#define IDC_LIST_TODEC_SEQ              1031
#define IDC_EDIT_SHELL_ARG1             1032
#define IDC_LIST_OBJECT                 1032
#define IDC_EDIT_SHELL_ARG2             1033
#define IDC_BUTTON_TODEC_ADD            1033
#define IDC_EDIT_SHELL_ARG3             1034
#define IDC_BUTTON_LOAD                 1034
#define IDC_EDIT_SHELL_ARG4             1035
#define IDC_STATIC_TODEC_SEQ_DESCR      1035
#define IDC_BUTTON_SHELL_CODE_GEN       1036
#define IDC_BUTTON_NEW                  1036
#define IDC_STATIC_SHELL_ARG1           1037
#define IDC_BUTTON_PUBLISH              1037
#define IDC_STATIC_SHELL_ARG2           1038
#define IDC_BUTTON_INCLUDE_ADD          1038
#define IDC_STATIC_SHELL_ARG3           1039
#define IDC_BUTTON_INCLUDE_DEL          1039
#define IDC_STATIC_PARSER_ARG8          1040
#define IDC_STATIC_SHELL_ARG4           1040
#define IDC_BUTTON_TODEC_DEL2           1040
#define IDC_BUTTON_OBJECT_DEL           1040
#define IDC_BUTTON_TODEC                1041
#define IDC_BUTTON_TODEC2               1042
#define IDC_BUTTON_KEYGEN               1042
#define IDC_COMBO_ENDIAN                1043
#define IDC_EDIT_STR                    1044
#define IDC_STATIC_BOX                  1045
#define IDC_BUTTON_CANCEL               1046
#define IDC_BUTTON_YES                  1047
#define IDC_EDIT_TEXT                   1048
#define IDC_RADIO_ONE_MEMBER_OF_STRUCTURE 1049
#define IDC_COMBO_ONE_MEMBER_OF_STRUCTURE 1050
#define IDC_COMBO_ONE_MEMBER_OF_STRUCTURE_METHOD 1051
#define IDC_RADIO_BYTES_OF_PRIMITIVE    1052
#define IDC_SLIDER_BITS_OF_PRIMITIVE_LEN 1053
#define IDC_SLIDER_BITS_OF_PRIMITIVE_SFT 1054
#define IDC_SLIDER_BYTES_OF_PRIMITIVE_LEN 1055
#define IDC_SLIDER_BYTES_OF_PRIMITIVE_SFT 1056
#define IDC_RADIO_INHIVIT_MEMBER        1057
#define IDC_RADIO_ALTERNATE_FUNCTION    1058
#define IDC_BUTTON_ONE_MEMBER_OF_STRUCTURE 1060
#define IDC_RADIO_BITS_OF_PRIMITIVE     1061
#define IDC_RADIO_SUB_BYTES_OF_PRIMITIVE 1064
#define IDC_SLIDER_SUB_BYTES_OF_PRIMITIVE_SFT 1066
#define IDC_RADIO_USE_ALTERNATIVE_FUNCTION 1067
#define IDC_EDIT_ALTERNATIVE_FUNCTION   1068
#define IDC_RADIO_DEFAULT_METHOD        1069
#define IDC_EDIT_ONE_OF_STRUCTURE       1070
#define IDC_CHECK_HEADER                1071
#define IDC_EDIT_HEADER                 1072
#define IDC_CHECK_SOURCE                1073
#define IDC_EDIT_SOURCE                 1074
#define IDC_BUTTON_HEADER               1075
#define IDC_LIST_INCLUDE                1076
#define IDC_COMBO_INCLUDE               1077
#define IDC_COMBO_TODEC                 1078

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        140
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1078
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
