#ifndef TRAFFIC_SIGNAL_CONTROLLER_TEST_SCENARIO_MSG_H_LOCAL
#define TRAFFIC_SIGNAL_CONTROLLER_TEST_SCENARIO_MSG_H_LOCAL

#define TRAFFIC_SIGNAL_CONTROLLER_TEST_SCENARIO_CORE_MSG			0xF0000000
#define TRAFFIC_SIGNAL_CONTROLLER_TEST_SCENARIO_DO_DEFAULT			(TRAFFIC_SIGNAL_CONTROLLER_TEST_SCENARIO_CORE_MSG | 0x00000001)
#define TRAFFIC_SIGNAL_CONTROLLER_TEST_SCENARIO_TRIGGER				(TRAFFIC_SIGNAL_CONTROLLER_TEST_SCENARIO_CORE_MSG | 0x0000000FF)


#define	TRAFFIC_SIGNAL_CONTROLLER_TEST_SCENARIO_COMMAND_MSG			0x0F000000
#define TRAFFIC_SIGNAL_CONTROLLER_TEST_SCENARIO_START				(TRAFFIC_SIGNAL_CONTROLLER_TEST_SCENARIO_COMMAND_MSG | 0x00000001)
#define TRAFFIC_SIGNAL_CONTROLLER_TEST_SCENARIO_STOP				(TRAFFIC_SIGNAL_CONTROLLER_TEST_SCENARIO_COMMAND_MSG | 0x00000002)
#define TRAFFIC_SIGNAL_CONTROLLER_TEST_SCENARIO_SETUP				(TRAFFIC_SIGNAL_CONTROLLER_TEST_SCENARIO_COMMAND_MSG | 0x00000003)


#define TRAFFIC_SIGNAL_CONTROLLER_TEST_SCENARIO_IPC_MSG				0x00F00000
// NOTIFY
#define TRAFFIC_SIGNAL_CONTROLLER_TEST_SCENARIO_NOTIFY_STATE		(TRAFFIC_SIGNAL_CONTROLLER_TEST_SCENARIO_IPC_MSG | 0x00000001)
#define TRAFFIC_SIGNAL_CONTROLLER_TEST_SCENARIO_NOTIFY_INFO			(TRAFFIC_SIGNAL_CONTROLLER_TEST_SCENARIO_IPC_MSG | 0x00000002)
#define TRAFFIC_SIGNAL_CONTROLLER_TEST_SCENARIO_NOTIFY_ERROR		(TRAFFIC_SIGNAL_CONTROLLER_TEST_SCENARIO_IPC_MSG | 0x00000003)
// VALIDATE
#define TRAFFIC_SIGNAL_CONTROLLER_TEST_SCENARIO_VALIDATE_REQUEST 	(TRAFFIC_SIGNAL_CONTROLLER_TEST_SCENARIO_IPC_MSG | 0x00000004)
#define TRAFFIC_SIGNAL_CONTROLLER_TEST_SCENARIO_VALIDATE_RESPONSE	(TRAFFIC_SIGNAL_CONTROLLER_TEST_SCENARIO_IPC_MSG | 0x00000005)
// INITIALIZE
#define TRAFFIC_SIGNAL_CONTROLLER_TEST_SCENARIO_UI_CONFIGURE		(TRAFFIC_SIGNAL_CONTROLLER_TEST_SCENARIO_IPC_MSG | 0x00000006)

#define TRAFFIC_SIGNAL_CONTROLLER_TEST_SCENARIO_SEND_DONE			(TRAFFIC_SIGNAL_CONTROLLER_TEST_SCENARIO_IPC_MSG | 0x0000000F)

#define TRAFFIC_SIGNAL_CONTROLLER_TEST_SCENARIO_TEST_MSG			0x0000F000
#define TRAFFIC_SIGNAL_CONTROLLER_TEST_SCENARIO_TEST_ENCODE			(TRAFFIC_SIGNAL_CONTROLLER_TEST_SCENARIO_TEST_MSG | 0x00000001)
#define TRAFFIC_SIGNAL_CONTROLLER_TEST_SCENARIO_TEST_DECODE			(TRAFFIC_SIGNAL_CONTROLLER_TEST_SCENARIO_TEST_MSG | 0x00000002)

#include "TrafficSignalControllerTestScenarioMsgs.h"


DZ1_CPPLINK bool_t TrafficSignalControllerTestScenario_commandMsgInit(void* task, Dz1Error* err);
DZ1_CPPLINK bool_t TrafficSignalControllerTestScenario_sockMsgInit(void* task, Dz1Error* err);

#endif // TRAFFIC_SIGNAL_CONTROLLER_TEST_SCENARIO_MSG_H_LOCAL
