#ifndef _ASN1_XER_UTF8STRING_H
#define _ASN1_XER_UTF8STRING_H

#include "ASN1_XER_STRING.h"

/*UTF8String */
#ifdef AVIOD_NAME_COLLISION_UTF8_STRING
ASN1_CPPLINK ASNINT32 ASN1_XER_CANONICAL_Enc_UTF8Str(ASN1WorkSpace * ws, UTF8Str *tvalue, ASNUINT8 *name,ASNINT32 tab_value);
ASN1_CPPLINK ASNINT32 ASN1_XER_BASIC_Enc_UTF8Str(ASN1WorkSpace * ws, UTF8Str *tvalue,	ASNUINT8 *name,ASNINT32 tab_value);
ASN1_CPPLINK ASNINT32 ASN1_XER_CANONICAL_Dec_UTF8Str(ASN1WorkSpace * ws, UTF8Str *value, ASNUINT8 *name,ASNINT32 tab_value);
ASN1_CPPLINK ASNINT32 ASN1_XER_BASIC_Dec_UTF8Str(ASN1WorkSpace * ws, UTF8Str *value, ASNUINT8 *name,ASNINT32 tab_value);
#else
ASN1_CPPLINK ASNINT32 ASN1_XER_CANONICAL_Enc_UTF8String(ASN1WorkSpace * ws, UTF8String *tvalue, ASNUINT8 *name,ASNINT32 tab_value);
ASN1_CPPLINK ASNINT32 ASN1_XER_BASIC_Enc_UTF8String(ASN1WorkSpace * ws, UTF8String *tvalue,	ASNUINT8 *name,ASNINT32 tab_value);
ASN1_CPPLINK ASNINT32 ASN1_XER_CANONICAL_Dec_UTF8String(ASN1WorkSpace * ws, UTF8String *value, ASNUINT8 *name,ASNINT32 tab_value);
ASN1_CPPLINK ASNINT32 ASN1_XER_BASIC_Dec_UTF8String(ASN1WorkSpace * ws, UTF8String *value, ASNUINT8 *name,ASNINT32 tab_value);
#endif // AVIOD_NAME_COLLISION_UTF8_STRING

#endif
