#ifndef DZ1_TCP_SERIAL_SERVER_SERIAL_IO_MSG_H_LOCAL
#define DZ1_TCP_SERIAL_SERVER_SERIAL_IO_MSG_H_LOCAL

#define DZ1_TCP_SERIAL_SERVER_SERIAL_IO_MSG				0x10000000

#define DZ1_TCP_SERIAL_SERVER_SERIAL_RECEIVED			(DZ1_TCP_SERIAL_SERVER_SERIAL_IO_MSG | 0x00000001)
#define DZ1_TCP_SERIAL_SERVER_SERIAL_RING_IND			(DZ1_TCP_SERIAL_SERVER_SERIAL_IO_MSG | 0x00000002)
#define DZ1_TCP_SERIAL_SERVER_SERIAL_CTS_CHANGED		(DZ1_TCP_SERIAL_SERVER_SERIAL_IO_MSG | 0x00000003)
#define DZ1_TCP_SERIAL_SERVER_SERIAL_DSR_CHANGED		(DZ1_TCP_SERIAL_SERVER_SERIAL_IO_MSG | 0x00000004)
#define DZ1_TCP_SERIAL_SERVER_SERIAL_EXCEPTION			(DZ1_TCP_SERIAL_SERVER_SERIAL_IO_MSG | 0x0000FFFF)

#include "Dz1TcpSerialServerSerialIOMsgs.h"

#endif