#ifndef DZ1_TCP_SERIAL_SERVER_MSG_H_LOCAL
#define DZ1_TCP_SERIAL_SERVER_MSG_H_LOCAL

#define DZ1_TCP_SERIAL_SERVER_CORE_MSG				0xF0000000
#define DZ1_TCP_SERIAL_SERVER_DO_DEFAULT			(DZ1_TCP_SERIAL_SERVER_CORE_MSG | 0x00000001)

#include "Dz1TcpSerialServerMsgs.h"

#endif
