#ifndef DZ1_TCP_CALLBACK_SERVER_MSG_H_LOCAL
#define DZ1_TCP_CALLBACK_SERVER_MSG_H_LOCAL

#define DZ1_TCP_CALLBACK_SERVER_CORE_MSG				0xF0000000
#define DZ1_TCP_CALLBACK_SERVER_DO_DEFAULT				(DZ1_TCP_CALLBACK_SERVER_CORE_MSG | 0x00000001)

#define DZ1_TCP_CALLBACK_SERVER_ACCEPTOR_MSG			0x10000000
#define DZ1_TCP_CALLBACK_SERVER_ACCEPTOR_CONNECTED		(DZ1_TCP_CALLBACK_SERVER_ACCEPTOR_MSG | 0x00000001)
#define DZ1_TCP_CALLBACK_SERVER_ACCEPTOR_EXCEPTION		(DZ1_TCP_CALLBACK_SERVER_ACCEPTOR_MSG | 0x0000FFFF)

#define DZ1_TCP_CALLBACK_SERVER_RECEIVER_MSG			0x20000000
#define DZ1_TCP_CALLBACK_SERVER_RECEIVER_RECEIVED		(DZ1_TCP_CALLBACK_SERVER_RECEIVER_MSG | 0x00000001)
#define DZ1_TCP_CALLBACK_SERVER_RECEIVER_DISCONNECTED	(DZ1_TCP_CALLBACK_SERVER_RECEIVER_MSG | 0x0000FFFF)

#define DZ1_TCP_CALLBACK_SERVER_SENDER_MSG				0x30000000
#define DZ1_TCP_CALLBACK_SERVER_SENDER_SENT				(DZ1_TCP_CALLBACK_SERVER_SENDER_MSG | 0x00000001)
#define DZ1_TCP_CALLBACK_SERVER_SENDER_EXCEPTION		(DZ1_TCP_CALLBACK_SERVER_SENDER_MSG | 0x0000FFFF)

#include "Dz1TcpCallbackServerMsgs.h"


#endif
